### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by wzagrajcz** [exxcellent/olingo-jpa-processor-v4#12]
Hello,

Do You have plans to publish this project into maven repository? This project is very promising and I'm thinking about using it in my project. Using it as regular maven dependency definitely would be a nice thing to have.

Thanks in advance

**Comment by rzozmann** [comment]
As written in https://github.com/exxcellent/olingo-jpa-processor-v4/blob/eXXcellent_adaptions/doc/integrators/GetStarted.md you can take the binaries from an alternative maven2 compatible repository at https://packagecloud.io/exxcellent/olingo-jpa-processor-v4/maven2.
But be aware: on that location only the latest version is published... so you need an additional Nexus/Maven-Repository-Proxy to save older version for production environment.

Why our binaries are not hosted on maven central?
Because we are only a fork... Currently we doesn't want to steal the namespace 'org.apache.olingo.jpa' (group id) from the SAP based original. So if we decide to publish to maven central (or other public repository) we have to give up the option to merge back our code into the SAP original github project. Currently only the root POM is using our company namespace...

**Comment by mgwoj** [comment]
Hello, 

What are the chances to merge back you code into the original library?

Thanks,
Michał

**Comment by rzozmann** [comment]
Most of the code is touched in any way, so we currently see no chance to merge back. We still provide our own binary artifacts and delay the the decision to an later moment...
